import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HeroLanding from '@/components/HeroLanding'
import NavBar from '@/components/NavBar'
import Spacer from '@/components/Spacer'
import CardElement from '@/components/CardElement'
import TestimonialSlider from '@/components/TestimonialSlider'
import ContactUsForm from '@/components/ContactUsForm'
import Footer from '@/components/Footer'
import { useEffect } from 'react'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import AboutUsContainer from '@/components/AboutUsContainer'
import CapabilitiesContainer from '@/components/CapabilitiesContainer'
import TestimonialSection from '@/components/TestimonialSection'
import ContactUs from '@/components/ContactUs'
import AboutHero from '@/components/AboutHero'
import AboutIntro from '@/components/AboutIntro'
import AboutCapabilities from '@/components/AboutCapabilities'
import AboutValues from '@/components/AboutValues'
import AboutContact from '@/components/AboutContact'
const inter = Inter({ subsets: ['latin'] })

const AboutUs = () => {

  
  useEffect(() => {
    document.body.scrollTop = 0;
    var myNav = document.getElementById('navbar');
    document.addEventListener('scroll', () => {
      let scrollTop =  window.scrollY;
      if (scrollTop >= 1 ) {
        myNav.classList.add("filled");
      } 
      else {
          myNav.classList.remove("filled");
      }
    })

  }, [])
  return (
    <>
      <Head>
        <title>Gen Z Consulting | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col relative">
        <NavBar/>
        
        <AboutHero/>
        
        <AboutIntro/>


        <AboutCapabilities/>

        <Spacer/>

        <AboutValues/>

        <Spacer/>

        <AboutContact/>
        <Footer></Footer>
      </main>
    </>
  )
}

export default AboutUs