import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HeroLanding from '@/components/HeroLanding'
import NavBar from '@/components/NavBar'
import Spacer from '@/components/Spacer'
import CardElement from '@/components/CardElement'
import TestimonialSlider from '@/components/TestimonialSlider'
import ContactUsForm from '@/components/ContactUsForm'
import Footer from '@/components/Footer'
import { useEffect } from 'react'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import CapabilityHero from '@/components/CapabilityHero'
import ExcelSection from '@/components/ExcelSection'
import TASSection from '@/components/TASSection'
import TASSuccesses from '@/components/TASSuccesses'
import HRConsulting from '@/components/HRConsulting'
import BusinessManagement from '@/components/BusinessManagement'
import FinancialManagement from '@/components/FinancialManagement'
import GovConServices from '@/components/GovConServices'
import CallToActionCapabilities from '@/components/CallToActionCapabilities'

const inter = Inter({ subsets: ['latin'] })

export default function Capabilities() {

  useEffect(() => {
    document.body.scrollTop = 0;
    var myNav = document.getElementById('navbar');
    document.addEventListener('scroll', () => {
      let scrollTop =  window.scrollY;
      if (scrollTop >= 1 ) {
        myNav.classList.add("filled");
      } 
      else {
          myNav.classList.remove("filled");
      }
    })

  }, [])
  
  return (
    <>
      <Head>
        <title>Gen Z Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col relative">
        <NavBar/>
        <CapabilityHero></CapabilityHero>

        <ExcelSection/>

        <TASSection></TASSection>

        <Spacer></Spacer>

        <TASSuccesses/>

        <Spacer id="human-resources"></Spacer>
        <HRConsulting/>
        <div id="business-management"></div>
        <BusinessManagement/>
        <div id="financial-management"></div>
        <FinancialManagement/>

        <GovConServices/>

        <CallToActionCapabilities/>

        <Footer></Footer>
      </main>
    </>
  )
}
